param(
  [string]$DistDir = (Join-Path $PSScriptRoot "..\dashboard\dist"),
  [string]$OutputFile = (Join-Path $PSScriptRoot "..\wix\GeneratedFiles.wxs")
)

$distDir = (Resolve-Path $DistDir).Path
$outputDir = Split-Path $OutputFile -Parent
if (-not (Test-Path $outputDir)) { New-Item -ItemType Directory -Path $outputDir -Force | Out-Null }

$files = Get-ChildItem -Recurse -File $distDir | Where-Object {
  $_.FullName -notmatch '\\backend\\' -and
  $_.FullName -notmatch '\\bundle\\' -and
  $_.FullName -notmatch '\\runtime\\'
}

$components = @()
foreach ($file in $files) {
  $relPath = $file.FullName.Substring($distDir.Length + 1)
  # Normalize to forward slashes for WiX
  $sourcePath = $relPath -replace '\\', '/'
  $parts = $relPath -split '\\'
  $fileName = $parts[-1]

  if ($parts -contains 'assets') {
    $targetDir = "ASSETS_DIR"
  } elseif ($parts[-2] -eq 'frontend') {
    $targetDir = "FRONTEND_DIR"
  } else {
    continue
  }

  $safeId = "f_" + ($fileName -replace '[^a-zA-Z0-9_]', '_')
  $components += "    <Component Id=`"$safeId`" Guid=`"*`"><File Id=`"$safeId`" Name=`"$fileName`" Source=`"$sourcePath`" KeyPath=`"yes`" /></Component>"
}

$content = "<?xml version=`"1.0`" encoding=`"utf-8`"?>
<Wix xmlns=`"http://wixtoolset.org/schemas/v4/wxs`">
  <Fragment>
    <ComponentGroup Id=`"AutoGeneratedFrontend`" Directory=`"FRONTEND_DIR`">
$($components -join "`r`n")
    </ComponentGroup>
  </Fragment>
</Wix>
"

[System.IO.File]::WriteAllText($OutputFile, $content, [System.Text.Encoding]::UTF8)
Write-Output "Generated $OutputFile with $($components.Count) file entries"
