version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    gosec:
      excludes:
        - G117 # to exclude 'Exported struct field "APISecret" (JSON key "APISecret") matches secret pattern'

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
